const communities = {
    "Andalusia": { name: "Andalucía", city: "Sevilla,ES" },
    "Aragon": { name: "Aragón", city: "Zaragoza,ES" },
    "Asturias": { name: "Asturias", city: "Oviedo,ES" },
    "Balearic Islands": { name: "Islas Baleares", city: "Palma,ES" },
    "Basque Country": { name: "País Vasco", city: "Bilbao,ES" },
    "Canary Islands": { name: "Islas Canarias", city: "Las Palmas de Gran Canaria,ES" },
    "Cantabria": { name: "Cantabria", city: "Santander,ES" },
    "Castile and Leon": { name: "Castilla y León", city: "Valladolid,ES" },
    "Castile-La Mancha": { name: "Castilla-La Mancha", city: "Toledo,ES" },
    "Catalonia": { name: "Cataluña", city: "Barcelona,ES" },
    "Extremadura": { name: "Extremadura", city: "Mérida,ES" },
    "Galicia": { name: "Galicia", city: "Santiago de Compostela,ES" },
    "La Rioja": { name: "La Rioja", city: "Logroño,ES" },
    "Madrid": { name: "Madrid", city: "Madrid,ES" },
    "Murcia": { name: "Región de Murcia", city: "Murcia,ES" },
    "Navarra": { name: "Navarra", city: "Pamplona,ES" },
    "Valencia": { name: "Valencia", city: "Valencia,ES" },
    "Ceuta": { name: "Ceuta", city: "Ceuta,ES" },
    "Melilla": { name: "Melilla", city: "Melilla,ES" },
};
export default communities;