// Lista de países estática con sus datos

const CountryList = [
    { name: "Afghanistan", nombre: "Afganistán", code: "AF", region: "Asia", regionCode: "ASI", capital: "Kabul" },
    { name: "Albania", nombre: "Albania", code: "AL", region: "Europe", regionCode: "EUR", capital: "Tirana" },
    { name: "Algeria", nombre: "Argelia", code: "DZ", region: "Africa", regionCode: "AFR", capital: "Argel" },
    { name: "American Samoa", nombre: "Samoa Americana", code: "AS", region: "Oceania", regionCode: "OCN", capital: "Pago Pago" },
    { name: "Andorra", nombre: "Andorra", code: "AD", region: "Europe", regionCode: "EUR", capital: "Andorra la Vella" },
    { name: "Angola", nombre: "Angola", code: "AO", region: "Africa", regionCode: "AFR", capital: "Luanda" },
    { name: "Anguilla", nombre: "Anguila", code: "AI", region: "Central America", regionCode: "CAC", capital: "The Valley" },
    { name: "Antarctica", nombre: "Antártida", code: "AQ", region: "Antarctica", regionCode: "ANT", capital: "No tiene capital" },
    { name: "Antigua and Barbuda", nombre: "Antigua y Barbuda", code: "AG", region: "Central America", regionCode: "CAC", capital: "Saint John's" },
    { name: "Argentina", nombre: "Argentina", code: "AR", region: "South America", regionCode: "SAM", capital: "Buenos Aires" },
    { name: "Armenia", nombre: "Armenia", code: "AM", region: "Asia", regionCode: "ASI", capital: "Ereván" },
    { name: "Aruba", nombre: "Aruba", code: "AW", region: "Central America", regionCode: "CAC", capital: "Oranjestad" },
    { name: "Australia", nombre: "Australia", code: "AU", region: "Oceania", regionCode: "OCN", capital: "Canberra" },
    { name: "Austria", nombre: "Austria", code: "AT", region: "Europe", regionCode: "EUR", capital: "Viena" },
    { name: "Azerbaijan", nombre: "Azerbaiyán", code: "AZ", region: "Asia", regionCode: "ASI", capital: "Bakú" },
    { name: "Bahamas, The", nombre: "Bahamas", code: "BS", region: "Central America", regionCode: "CAC", capital: "Nassau" },
    { name: "Bahrain", nombre: "Baréin", code: "BH", region: "Middle East", regionCode: "MEA", capital: "Manama" },
    { name: "Bangladesh", nombre: "Bangladesh", code: "BD", region: "Asia", regionCode: "ASI", capital: "Dhaka" },
    { name: "Barbados", nombre: "Barbados", code: "BB", region: "Central America", regionCode: "CAC", capital: "Bridgetown" },
    { name: "Belarus", nombre: "Bielorrusia", code: "BY", region: "Europe", regionCode: "EUR", capital: "Minsk" },
    { name: "Belgium", nombre: "Bélgica", code: "BE", region: "Europe", regionCode: "EUR", capital: "Bruselas" },
    { name: "Belize", nombre: "Belice", code: "BZ", region: "Central America", regionCode: "CAC", capital: "Belmopan" },
    { name: "Benin", nombre: "Benín", code: "BJ", region: "Africa", regionCode: "AFR", capital: "Porto-Novo" },
    { name: "Bermuda", nombre: "Bermudas", code: "BM", region: "North America", regionCode: "NAM", capital: "Hamilton" },
    { name: "Bhutan", nombre: "Bután", code: "BT", region: "Asia", regionCode: "ASI", capital: "Thimphu" },
    { name: "Bolivia", nombre: "Bolivia", code: "BO", region: "South America", regionCode: "SAM", capital: "Sucre" },
    { name: "Bonaire", nombre: "Bonaire", code: "BQ", region: "Central America", regionCode: "CAC", capital: "Kralendijk" },
    { name: "Bosnia and Herzegovina", nombre: "Bosnia y Herzegovina", code: "BA", region: "Europe", regionCode: "EUR", capital: "Sarajevo" },
    { name: "Botswana", nombre: "Botsuana", code: "BW", region: "Africa", regionCode: "AFR", capital: "Gaborone" },
    { name: "Bouvet Island", nombre: "Isla Bouvet", code: "BV", region: "Antarctica", regionCode: "ANT", capital: "No tiene capital" },
    { name: "Brazil", nombre: "Brasil", code: "BR", region: "South America", regionCode: "SAM", capital: "Brasilia" },
    { name: "British Indian Ocean Territory", nombre: "Territorio Británico del Océano Índico", code: "IO", region: "Asia", regionCode: "ASI", capital: "No tiene capital" },
    { name: "British Virgin Islands", nombre: "Islas Vírgenes Británicas", code: "VG", region: "Central America", regionCode: "CAC", capital: "Road Town" },
    { name: "Brunei", nombre: "Brunéi", code: "BN", region: "Asia", regionCode: "ASI", capital: "Bandar Seri Begawan" },
    { name: "Bulgaria", nombre: "Bulgaria", code: "BG", region: "Europe", regionCode: "EUR", capital: "Sofía" },
    { name: "Burkina Faso", nombre: "Burkina Faso", code: "BF", region: "Africa", regionCode: "AFR", capital: "Uagadugú" },
    { name: "Burundi", nombre: "Burundi", code: "BI", region: "Africa", regionCode: "AFR", capital: "Gitega" },
    { name: "Cambodia", nombre: "Camboya", code: "KH", region: "Asia", regionCode: "ASI", capital: "Phnom Penh" },
    { name: "Cameroon", nombre: "Camerún", code: "CM", region: "Africa", regionCode: "AFR", capital: "Yaundé" },
    { name: "Canada", nombre: "Canadá", code: "CA", region: "North America", regionCode: "NAM", capital: "Ottawa" },
    { name: "Cape Verde", nombre: "Cabo Verde", code: "CV", region: "Africa", regionCode: "AFR", capital: "Praia" },
    { name: "Cayman Islands", nombre: "Islas Caimán", code: "KY", region: "Central America", regionCode: "CAC", capital: "George Town" },
    { name: "Central African Republic", nombre: "República Centroafricana", code: "CF", region: "Africa", regionCode: "AFR", capital: "Bangui" },
    { name: "Chad", nombre: "Chad", code: "TD", region: "Africa", regionCode: "AFR", capital: "N'Djamena" },
    { name: "Chile", nombre: "Chile", code: "CL", region: "South America", regionCode: "SAM", capital: "Santiago" },
    { name: "China", nombre: "China", code: "CN", region: "Asia", regionCode: "ASI", capital: "Beijing" },
    { name: "Christmas Island", nombre: "Isla de Navidad", code: "CX", region: "Asia", regionCode: "ASI", capital: "No tiene capital" },
    { name: "Cocos (Keeling) Islands", nombre: "Islas Cocos (Keeling)", code: "CC", region: "Asia", regionCode: "ASI", capital: "No tiene capital" },
    { name: "Colombia", nombre: "Colombia", code: "CO", region: "South America", regionCode: "SAM", capital: "Bogotá" },
    { name: "Comoros", nombre: "Comoras", code: "KM", region: "Africa", regionCode: "AFR", capital: "Moroni" },
    { name: "Congo (Congo-Brazzaville)", nombre: "Congo (Congo-Brazzaville)", code: "CG", region: "Africa", regionCode: "AFR", capital: "Brazzaville" },
    { name: "Congo (Democratic Republic)", nombre: "Congo (República Democrática)", code: "CD", region: "Africa", regionCode: "AFR", capital: "Kinshasa" },
    { name: "Cook Islands", nombre: "Islas Cook", code: "CK", region: "Oceania", regionCode: "OCN", capital: "Avarua" },
    { name: "Costa Rica", nombre: "Costa Rica", code: "CR", region: "Central America", regionCode: "CAC", capital: "San José" },
    { name: "Croatia", nombre: "Croacia", code: "HR", region: "Europe", regionCode: "EUR", capital: "Zagreb" },
    { name: "Cuba", nombre: "Cuba", code: "CU", region: "Central America", regionCode: "CAC", capital: "La Habana" },
    { name: "Curaçao", nombre: "Curazao", code: "CW", region: "Central America", regionCode: "CAC", capital: "Willemstad" },
    { name: "Cyprus", nombre: "Chipre", code: "CY", region: "Europe", regionCode: "EUR", capital: "Nicosia" },
    { name: "Czech Republic (Czechia)", nombre: "República Checa (Chequia)", code: "CZ", region: "Europe", regionCode: "EUR", capital: "Praga" },
    { name: "Denmark", nombre: "Dinamarca", code: "DK", region: "Europe", regionCode: "EUR", capital: "Copenhague" },
    { name: "Djibouti", nombre: "Yibuti", code: "DJ", region: "Africa", regionCode: "AFR", capital: "Yibuti" },
    { name: "Dominica", nombre: "Dominica", code: "DM", region: "Caribbean", regionCode: "CAR", capital: "Roseau" },
    { name: "Dominican Republic", nombre: "República Dominicana", code: "DO", region: "Caribbean", regionCode: "CAR", capital: "Santo Domingo" },
    { name: "Ecuador", nombre: "Ecuador", code: "EC", region: "South America", regionCode: "SAM", capital: "Quito" },
    { name: "Egypt", nombre: "Egipto", code: "EG", region: "Africa", regionCode: "AFR", capital: "El Cairo" },
    { name: "El Salvador", nombre: "El Salvador", code: "SV", region: "Central America", regionCode: "CAC", capital: "San Salvador" },
    { name: "Equatorial Guinea", nombre: "Guinea Ecuatorial", code: "GQ", region: "Africa", regionCode: "AFR", capital: "Malabo" },
    { name: "Eritrea", nombre: "Eritrea", code: "ER", region: "Africa", regionCode: "AFR", capital: "Asmara" },
    { name: "Estonia", nombre: "Estonia", code: "EE", region: "Europe", regionCode: "EUR", capital: "Tallin" },
    { name: "Eswatini", nombre: "Esuatini", code: "SZ", region: "Africa", regionCode: "AFR", capital: "Mbabane" },
    { name: "Ethiopia", nombre: "Etiopía", code: "ET", region: "Africa", regionCode: "AFR", capital: "Adís Abeba" },
    { name: "Falkland Islands", nombre: "Islas Malvinas", code: "FK", region: "South America", regionCode: "SAM", capital: "Stanley" },
    { name: "Faroe Islands", nombre: "Islas Feroe", code: "FO", region: "Europe", regionCode: "EUR", capital: "Tórshavn" },
    { name: "Fiji", nombre: "Fiyi", code: "FJ", region: "Oceania", regionCode: "OCN", capital: "Suva" },
    { name: "Finland", nombre: "Finlandia", code: "FI", region: "Europe", regionCode: "EUR", capital: "Helsinki" },
    { name: "France", nombre: "Francia", code: "FR", region: "Europe", regionCode: "EUR", capital: "París" },
    { name: "Gabon", nombre: "Gabón", code: "GA", region: "Africa", regionCode: "AFR", capital: "Libreville" },
    { name: "Gambia, The", nombre: "Gambia", code: "GM", region: "Africa", regionCode: "AFR", capital: "Banjul" },
    { name: "Georgia", nombre: "Georgia", code: "GE", region: "Asia", regionCode: "ASI", capital: "Tiflis" },
    { name: "Germany", nombre: "Alemania", code: "DE", region: "Europe", regionCode: "EUR", capital: "Berlin" },
    { name: "Ghana", nombre: "Ghana", code: "GH", region: "Africa", regionCode: "AFR", capital: "Accra" },
    { name: "Gibraltar", nombre: "Gibraltar", code: "GI", region: "Europe", regionCode: "EUR", capital: "Gibraltar" },
    { name: "Greece", nombre: "Grecia", code: "GR", region: "Europe", regionCode: "EUR", capital: "Athens" },
    { name: "Greenland", nombre: "Groenlandia", code: "GL", region: "North America", regionCode: "NAM", capital: "Nuuk" },
    { name: "Grenada", nombre: "Granada", code: "GD", region: "Caribbean", regionCode: "CAR", capital: "St. George's" },
    { name: "Guadeloupe", nombre: "Guadalupe", code: "GP", region: "Caribbean", regionCode: "CAR", capital: "Basse-Terre" },
    { name: "Guam", nombre: "Guam", code: "GU", region: "Oceania", regionCode: "OCN", capital: "Hagåtña" },
    { name: "Guatemala", nombre: "Guatemala", code: "GT", region: "Central America", regionCode: "CAC", capital: "Guatemala City" },
    { name: "Guernsey", nombre: "Guernsey", code: "GG", region: "Europe", regionCode: "EUR", capital: "St. Peter Port" },
    { name: "Guinea", nombre: "Guinea", code: "GN", region: "Africa", regionCode: "AFR", capital: "Conakry" },
    { name: "Guinea-Bissau", nombre: "Guinea-Bisáu", code: "GW", region: "Africa", regionCode: "AFR", capital: "Bissau" },
    { name: "Guyana", nombre: "Guyana", code: "GY", region: "South America", regionCode: "SAM", capital: "Georgetown" },
    { name: "Haiti", nombre: "Haití", code: "HT", region: "Caribbean", regionCode: "CAR", capital: "Port-au-Prince" },
    { name: "Heard Island and McDonald Islands", nombre: "Isla Heard y las Islas McDonald", code: "HM", region: "Antarctica", regionCode: "ANT", capital: "None" },
    { name: "Honduras", nombre: "Honduras", code: "HN", region: "Central America", regionCode: "CAC", capital: "Tegucigalpa" },
    { name: "Hong Kong", nombre: "Hong Kong", code: "HK", region: "Asia", regionCode: "ASI", capital: "Hong Kong" },
    { name: "Hungary", nombre: "Hungría", code: "HU", region: "Europe", regionCode: "EUR", capital: "Budapest" },
    { name: "Iceland", nombre: "Islandia", code: "IS", region: "Europe", regionCode: "EUR", capital: "Reykjavík" },
    { name: "India", nombre: "India", code: "IN", region: "Asia", regionCode: "ASI", capital: "New Delhi" },
    { name: "Indonesia", nombre: "Indonesia", code: "ID", region: "Asia", regionCode: "ASI", capital: "Jakarta" },
    { name: "Iran", nombre: "Irán", code: "IR", region: "Asia", regionCode: "ASI", capital: "Tehran" },
    { name: "Iraq", nombre: "Irak", code: "IQ", region: "Asia", regionCode: "ASI", capital: "Baghdad" },
    { name: "Ireland", nombre: "Irlanda", code: "IE", region: "Europe", regionCode: "EUR", capital: "Dublin" },
    { name: "Isle of Man", nombre: "Isla de Man", code: "IM", region: "Europe", regionCode: "EUR", capital: "Douglas" },
    { name: "Israel", nombre: "Israel", code: "IL", region: "Middle East", regionCode: "MEA", capital: "Jerusalem" },
    { name: "Italy", nombre: "Italia", code: "IT", region: "Europe", regionCode: "EUR", capital: "Rome" },
    { name: "Jamaica", nombre: "Jamaica", code: "JM", region: "Caribbean", regionCode: "CAR", capital: "Kingston" },
    { name: "Japan", nombre: "Japón", code: "JP", region: "Asia", regionCode: "ASI", capital: "Tokyo" },
    { name: "Jersey", nombre: "Jersey", code: "JE", region: "Europe", regionCode: "EUR", capital: "St. Helier" },
    { name: "Jordan", nombre: "Jordania", code: "JO", region: "Middle East", regionCode: "MEA", capital: "Amman" },
    { name: "Kazakhstan", nombre: "Kazajistán", code: "KZ", region: "Asia", regionCode: "ASI", capital: "Astana" },
    { name: "Kenya", nombre: "Kenia", code: "KE", region: "Africa", regionCode: "AFR", capital: "Nairobi" },
    { name: "Kiribati", nombre: "Kiribati", code: "KI", region: "Oceania", regionCode: "OCN", capital: "South Tarawa" },
    { name: "Korea, North", nombre: "Corea del Norte", code: "KP", region: "Asia", regionCode: "ASI", capital: "Pyongyang" },
    { name: "Korea, South", nombre: "Corea del Sur", code: "KR", region: "Asia", regionCode: "ASI", capital: "Seoul" },
    { name: "Kuwait", nombre: "Kuwait", code: "KW", region: "Middle East", regionCode: "MEA", capital: "Kuwait City" },
    { name: "Kyrgyzstan", nombre: "Kirguistán", code: "KG", region: "Asia", regionCode: "ASI", capital: "Bishkek" },
    { name: "Laos", nombre: "Laos", code: "LA", region: "Asia", regionCode: "ASI", capital: "Vientiane" },
    { name: "Latvia", nombre: "Letonia", code: "LV", region: "Europe", regionCode: "EUR", capital: "Riga" },
    { name: "Lebanon", nombre: "Líbano", code: "LB", region: "Middle East", regionCode: "MEA", capital: "Beirut" },
    { name: "Lesotho", nombre: "Lesoto", code: "LS", region: "Africa", regionCode: "AFR", capital: "Maseru" },
    { name: "Liberia", nombre: "Liberia", code: "LR", region: "Africa", regionCode: "AFR", capital: "Monrovia" },
    { name: "Libya", nombre: "Libia", code: "LY", region: "Africa", regionCode: "AFR", capital: "Tripoli" },
    { name: "Liechtenstein", nombre: "Liechtenstein", code: "LI", region: "Europe", regionCode: "EUR", capital: "Vaduz" },
    { name: "Lithuania", nombre: "Lituania", code: "LT", region: "Europe", regionCode: "EUR", capital: "Vilnius" },
    { name: "Luxembourg", nombre: "Luxemburgo", code: "LU", region: "Europe", regionCode: "EUR", capital: "Luxembourg City" },
    { name: "Macau", nombre: "Macao", code: "MO", region: "Asia", regionCode: "ASI", capital: "Macau" },
    { name: "Madagascar", nombre: "Madagascar", code: "MG", region: "Africa", regionCode: "AFR", capital: "Antananarivo" },
    { name: "Malawi", nombre: "Malawi", code: "MW", region: "Africa", regionCode: "AFR", capital: "Lilongwe" },
    { name: "Malaysia", nombre: "Malasia", code: "MY", region: "Asia", regionCode: "ASI", capital: "Kuala Lumpur" },
    { name: "Maldives", nombre: "Maldivas", code: "MV", region: "Asia", regionCode: "ASI", capital: "Malé" },
    { name: "Mali", nombre: "Malí", code: "ML", region: "Africa", regionCode: "AFR", capital: "Bamako" },
    { name: "Malta", nombre: "Malta", code: "MT", region: "Europe", regionCode: "EUR", capital: "Valletta" },
    { name: "Marshall Islands", nombre: "Islas Marshall", code: "MH", region: "Oceania", regionCode: "OCN", capital: "Majuro" },
    { name: "Martinique", nombre: "Martinica", code: "MQ", region: "Caribbean", regionCode: "CAR", capital: "Fort-de-France" },
    { name: "Mauritania", nombre: "Mauritania", code: "MR", region: "Africa", regionCode: "AFR", capital: "Nouakchott" },
    { name: "Mauritius", nombre: "Mauricio", code: "MU", region: "Africa", regionCode: "AFR", capital: "Port Louis" },
    { name: "Mayotte", nombre: "Mayotte", code: "YT", region: "Africa", regionCode: "AFR", capital: "Mamoudzou" },
    { name: "Mexico", nombre: "México", code: "MX", region: "North America", regionCode: "NAM", capital: "Mexico City" },
    { name: "Micronesia", nombre: "Micronesia", code: "FM", region: "Oceania", regionCode: "OCN", capital: "Palikir" },
    { name: "Moldova", nombre: "Moldavia", code: "MD", region: "Europe", regionCode: "EUR", capital: "Chisinau" },
    { name: "Monaco", nombre: "Mónaco", code: "MC", region: "Europe", regionCode: "EUR", capital: "Monaco" },
    { name: "Mongolia", nombre: "Mongolia", code: "MN", region: "Asia", regionCode: "ASI", capital: "Ulaanbaatar" },
    { name: "Montenegro", nombre: "Montenegro", code: "ME", region: "Europe", regionCode: "EUR", capital: "Podgorica" },
    { name: "Montserrat", nombre: "Montserrat", code: "MS", region: "Caribbean", regionCode: "CAR", capital: "Plymouth" },
    { name: "Morocco", nombre: "Marruecos", code: "MA", region: "Africa", regionCode: "AFR", capital: "Rabat" },
    { name: "Mozambique", nombre: "Mozambique", code: "MZ", region: "Africa", regionCode: "AFR", capital: "Maputo" },
    { name: "Myanmar", nombre: "Birmania", code: "MM", region: "Asia", regionCode: "ASI", capital: "Naypyidaw" },
    { name: "Namibia", nombre: "Namibia", code: "NA", region: "Africa", regionCode: "AFR", capital: "Windhoek" },
    { name: "Nauru", nombre: "Nauru", code: "NR", region: "Oceania", regionCode: "OCN", capital: "Yaren" },
    { name: "Nepal", nombre: "Nepal", code: "NP", region: "Asia", regionCode: "ASI", capital: "Kathmandu" },
    { name: "Netherlands", nombre: "Países Bajos", code: "NL", region: "Europe", regionCode: "EUR", capital: "Amsterdam" },
    { name: "New Caledonia", nombre: "Nueva Caledonia", code: "NC", region: "Oceania", regionCode: "OCN", capital: "Nouméa" },
    { name: "New Zealand", nombre: "Nueva Zelanda", code: "NZ", region: "Oceania", regionCode: "OCN", capital: "Wellington" },
    { name: "Nicaragua", nombre: "Nicaragua", code: "NI", region: "Central America", regionCode: "CAC", capital: "Managua" },
    { name: "Niger", nombre: "Níger", code: "NE", region: "Africa", regionCode: "AFR", capital: "Niamey" },
    { name: "Nigeria", nombre: "Nigeria", code: "NG", region: "Africa", regionCode: "AFR", capital: "Abuja" },
    { name: "Niue", nombre: "Niue", code: "NU", region: "Oceania", regionCode: "OCN", capital: "Alofi" },
    { name: "Norfolk Island", nombre: "Isla Norfolk", code: "NF", region: "Oceania", regionCode: "OCN", capital: "Kingston" },
    { name: "North Macedonia", nombre: "Macedonia del Norte", code: "MK", region: "Europe", regionCode: "EUR", capital: "Skopje" },
    { name: "Northern Mariana Islands", nombre: "Islas Marianas del Norte", code: "MP", region: "Oceania", regionCode: "OCN", capital: "Saipan" },
    { name: "Norway", nombre: "Noruega", code: "NO", region: "Europe", regionCode: "EUR", capital: "Oslo" },
    { name: "Oman", nombre: "Omán", code: "OM", region: "Middle East", regionCode: "MEA", capital: "Muscat" },
    { name: "Pakistan", nombre: "Pakistán", code: "PK", region: "Asia", regionCode: "ASI", capital: "Islamabad" },
    { name: "Palau", nombre: "Palaos", code: "PW", region: "Oceania", regionCode: "OCN", capital: "Ngerulmud" },
    { name: "Palestinian Territory", nombre: "Territorio Palestino", code: "PS", region: "Middle East", regionCode: "MEA", capital: "Ramallah" },
    { name: "Panama", nombre: "Panamá", code: "PA", region: "Central America", regionCode: "CAC", capital: "Panama City" },
    { name: "Papua New Guinea", nombre: "Papúa Nueva Guinea", code: "PG", region: "Oceania", regionCode: "OCN", capital: "Port Moresby" },
    { name: "Paraguay", nombre: "Paraguay", code: "PY", region: "South America", regionCode: "SAM", capital: "Asunción" },
    { name: "Peru", nombre: "Perú", code: "PE", region: "South America", regionCode: "SAM", capital: "Lima" },
    { name: "Philippines", nombre: "Filipinas", code: "PH", region: "Asia", regionCode: "ASI", capital: "Manila" },
    { name: "Pitcairn Islands", nombre: "Islas Pitcairn", code: "PN", region: "Oceania", regionCode: "OCN", capital: "Adamstown" },
    { name: "Poland", nombre: "Polonia", code: "PL", region: "Europe", regionCode: "EUR", capital: "Warsaw" },
    { name: "Portugal", nombre: "Portugal", code: "PT", region: "Europe", regionCode: "EUR", capital: "Lisbon" },
    { name: "Puerto Rico", nombre: "Puerto Rico", code: "PR", region: "Caribbean", regionCode: "CAR", capital: "San Juan" },
    { name: "Qatar", nombre: "Catar", code: "QA", region: "Middle East", regionCode: "MEA", capital: "Doha" },
    { name: "Réunion", nombre: "Reunión", code: "RE", region: "Africa", regionCode: "AFR", capital: "Saint-Denis" },
    { name: "Romania", nombre: "Rumanía", code: "RO", region: "Europe", regionCode: "EUR", capital: "Bucharest" },
    { name: "Russia", nombre: "Rusia", code: "RU", region: "Europe", regionCode: "EUR", capital: "Moscow" },
    { name: "Rwanda", nombre: "Ruanda", code: "RW", region: "Africa", regionCode: "AFR", capital: "Kigali" },
    { name: "Saint Barthélemy", nombre: "San Bartolomé", code: "BL", region: "Caribbean", regionCode: "CAR", capital: "Gustavia" },
    { name: "Saint Helena", nombre: "Santa Helena", code: "SH", region: "Africa", regionCode: "AFR", capital: "Jamestown" },
    { name: "Saint Kitts and Nevis", nombre: "San Cristóbal y Nieves", code: "KN", region: "Caribbean", regionCode: "CAR", capital: "Basseterre" },
    { name: "Saint Lucia", nombre: "Santa Lucía", code: "LC", region: "Caribbean", regionCode: "CAR", capital: "Castries" },
    { name: "Saint Martin", nombre: "San Martín", code: "MF", region: "Caribbean", regionCode: "CAR", capital: "Marigot" },
    { name: "Saint Pierre and Miquelon", nombre: "San Pedro y Miquelón", code: "PM", region: "North America", regionCode: "NAM", capital: "Saint-Pierre" },
    { name: "Saint Vincent and the Grenadines", nombre: "San Vicente y las Granadinas", code: "VC", region: "Caribbean", regionCode: "CAR", capital: "Kingstown" },
    { name: "Samoa", nombre: "Samoa", code: "WS", region: "Oceania", regionCode: "OCN", capital: "Apia" },
    { name: "San Marino", nombre: "San Marino", code: "SM", region: "Europe", regionCode: "EUR", capital: "San Marino" },
    { name: "Sao Tome and Principe", nombre: "Santo Tomé y Príncipe", code: "ST", region: "Africa", regionCode: "AFR", capital: "São Tomé" },
    { name: "Saudi Arabia", nombre: "Arabia Saudita", code: "SA", region: "Middle East", regionCode: "MEA", capital: "Riyadh" },
    { name: "Senegal", nombre: "Senegal", code: "SN", region: "Africa", regionCode: "AFR", capital: "Dakar" },
    { name: "Serbia", nombre: "Serbia", code: "RS", region: "Europe", regionCode: "EUR", capital: "Belgrade" },
    { name: "Seychelles", nombre: "Seychelles", code: "SC", region: "Africa", regionCode: "AFR", capital: "Victoria" },
    { name: "Sierra Leone", nombre: "Sierra Leona", code: "SL", region: "Africa", regionCode: "AFR", capital: "Freetown" },
    { name: "Singapore", nombre: "Singapur", code: "SG", region: "Asia", regionCode: "ASI", capital: "Singapore" },
    { name: "Sint Maarten", nombre: "Sint Maarten", code: "SX", region: "Caribbean", regionCode: "CAR", capital: "Philipsburg" },
    { name: "Slovakia", nombre: "Eslovaquia", code: "SK", region: "Europe", regionCode: "EUR", capital: "Bratislava" },
    { name: "Slovenia", nombre: "Eslovenia", code: "SI", region: "Europe", regionCode: "EUR", capital: "Ljubljana" },
    { name: "Solomon Islands", nombre: "Islas Salomón", code: "SB", region: "Oceania", regionCode: "OCN", capital: "Honiara" },
    { name: "Somalia", nombre: "Somalia", code: "SO", region: "Africa", regionCode: "AFR", capital: "Mogadishu" },
    { name: "South Africa", nombre: "Sudáfrica", code: "ZA", region: "Africa", regionCode: "AFR", capital: "Pretoria (administrative), Bloemfontein (judicial), Cape Town (legislative)" },
    { name: "South Georgia and the South Sandwich Islands", nombre: "Islas Georgias del Sur y Sandwich del Sur", code: "GS", region: "South America", regionCode: "SAM", capital: "King Edward Point" },
    { name: "South Korea", nombre: "Corea del Sur", code: "KR", region: "Asia", regionCode: "ASI", capital: "Seoul" },
    { name: "South Sudan", nombre: "Sudán del Sur", code: "SS", region: "Africa", regionCode: "AFR", capital: "Juba" },
    { name: "Spain", nombre: "España", code: "ES", region: "Europe", regionCode: "EUR", capital: "Madrid" },
    { name: "Sri Lanka", nombre: "Sri Lanka", code: "LK", region: "Asia", regionCode: "ASI", capital: "Sri Jayawardenepura Kotte (administrative), Colombo (commercial)" },
    { name: "Sudan", nombre: "Sudán", code: "SD", region: "Africa", regionCode: "AFR", capital: "Khartoum" },
    { name: "Suriname", nombre: "Surinam", code: "SR", region: "South America", regionCode: "SAM", capital: "Paramaribo" },
    { name: "Svalbard and Jan Mayen", nombre: "Svalbard y Jan Mayen", code: "SJ", region: "Europe", regionCode: "EUR", capital: "Longyearbyen" },
    { name: "Sweden", nombre: "Suecia", code: "SE", region: "Europe", regionCode: "EUR", capital: "Stockholm" },
    { name: "Switzerland", nombre: "Suiza", code: "CH", region: "Europe", regionCode: "EUR", capital: "Bern" },
    { name: "Syria", nombre: "Siria", code: "SY", region: "Asia", regionCode: "ASI", capital: "Damascus" },
    { name: "Taiwan", nombre: "Taiwán", code: "TW", region: "Asia", regionCode: "ASI", capital: "Taipei" },
    { name: "Tajikistan", nombre: "Tayikistán", code: "TJ", region: "Asia", regionCode: "ASI", capital: "Dushanbe" },
    { name: "Tanzania", nombre: "Tanzania", code: "TZ", region: "Africa", regionCode: "AFR", capital: "Dodoma" },
    { name: "Thailand", nombre: "Tailandia", code: "TH", region: "Asia", regionCode: "ASI", capital: "Bangkok" },
    { name: "Timor-Leste", nombre: "Timor Oriental", code: "TL", region: "Asia", regionCode: "ASI", capital: "Dili" },
    { name: "Togo", nombre: "Togo", code: "TG", region: "Africa", regionCode: "AFR", capital: "Lomé" },
    { name: "Tokelau", nombre: "Tokelau", code: "TK", region: "Oceania", regionCode: "OCN", capital: "Fakaofo" },
    { name: "Tonga", nombre: "Tonga", code: "TO", region: "Oceania", regionCode: "OCN", capital: "Nukuʻalofa" },
    { name: "Trinidad and Tobago", nombre: "Trinidad y Tobago", code: "TT", region: "Caribbean", regionCode: "CAR", capital: "Port of Spain" },
    { name: "Tunisia", nombre: "Túnez", code: "TN", region: "Africa", regionCode: "AFR", capital: "Tunis" },
    { name: "Turkey", nombre: "Turquía", code: "TR", region: "Europe", regionCode: "EUR", capital: "Ankara" },
    { name: "Turkmenistan", nombre: "Turkmenistán", code: "TM", region: "Asia", regionCode: "ASI", capital: "Ashgabat" },
    { name: "Tuvalu", nombre: "Tuvalu", code: "TV", region: "Oceania", regionCode: "OCN", capital: "Funafuti" },
    { name: "Uganda", nombre: "Uganda", code: "UG", region: "Africa", regionCode: "AFR", capital: "Kampala" },
    { name: "Ukraine", nombre: "Ucrania", code: "UA", region: "Europe", regionCode: "EUR", capital: "Kyiv" },
    { name: "United Arab Emirates", nombre: "Emiratos Árabes Unidos", code: "AE", region: "Middle East", regionCode: "MEA", capital: "Abu Dhabi" },
    { name: "United Kingdom", nombre: "Reino Unido", code: "GB", region: "Europe", regionCode: "EUR", capital: "London" },
    { name: "United States", nombre: "Estados Unidos", code: "US", region: "North America", regionCode: "NAM", capital: "Washington, D.C." },
    { name: "Uruguay", nombre: "Uruguay", code: "UY", region: "South America", regionCode: "SAM", capital: "Montevideo" },
    { name: "Uzbekistan", nombre: "Uzbekistán", code: "UZ", region: "Asia", regionCode: "ASI", capital: "Tashkent" },
    { name: "Vanuatu", nombre: "Vanuatu", code: "VU", region: "Oceania", regionCode: "OCN", capital: "Port Vila" },
    { name: "Vatican City", nombre: "Ciudad del Vaticano", code: "VA", region: "Europe", regionCode: "EUR", capital: "Vatican City" },
    { name: "Venezuela", nombre: "Venezuela", code: "VE", region: "South America", regionCode: "SAM", capital: "Caracas" },
    { name: "Vietnam", nombre: "Vietnam", code: "VN", region: "Asia", regionCode: "ASI", capital: "Hanoi" },
    { name: "Wallis and Futuna", nombre: "Wallis y Futuna", code: "WF", region: "Oceania", regionCode: "OCN", capital: "Mata-Utu" },
    { name: "Western Sahara", nombre: "Sahara Occidental", code: "EH", region: "Africa", regionCode: "AFR", capital: "Laayoune" },
    { name: "Yemen", nombre: "Yemen", code: "YE", region: "Middle East", regionCode: "MEA", capital: "Sana'a" },
    { name: "Zambia", nombre: "Zambia", code: "ZM", region: "Africa", regionCode: "AFR", capital: "Lusaka" },
    { name: "Zimbabwe", nombre: "Zimbabue", code: "ZW", region: "Africa", regionCode: "AFR", capital: "Harare" }   
  ]

export default CountryList;